### ISSUE TITLE
Osiraa requires  insufficient_verification reason but DRP specifies insuf_verification

### ISSUE THREAD

**Issue by tangrammer** [datarightsprotocol/osiraa#29]
Hi guys!

just double checking about which will be the final `reason`  string for insufficient verification. I'm getting error validations on OSIRAA when i try `insuf_verification` but works with `insufficient_verification`, on the other hand DRP specifies `insuf_verification`

DRP link https://github.com/consumer-reports-innovation-lab/data-rights-protocol?tab=readme-ov-file#302-request-statuses

**Comment by JohnSzingerCR** [comment]
Hi, I've updated the app to use insuf_verification in conformance with the spec.  I will post a new version soon.

**Comment by JohnSzingerCR** [comment]
Updates committed to code base.

**Comment by JohnSzingerCR** [comment]
Updates committed to code base.
